import type { Metadata } from "next"
import { Inter } from "next/font/google"

import "./globals.css"
import FrontendTracerProvider from "@/app/providers/frontend-tracer-provider"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Nhollas App",
  description: "Generated by create-nhollas-app",
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <FrontendTracerProvider>
      <html lang="en">
        <body className={inter.className}>
          <main className="mx-auto min-h-screen max-w-6xl space-y-8 p-8 lg:p-16">
            {children}
          </main>
        </body>
      </html>
    </FrontendTracerProvider>
  )
}
