# .github/workflows/main.yml
name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: apps/cli
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install dependencies
        run: |
          npm ci
          npx playwright install --with-deps
          npm install -g pnpm

      - name: Run prepublishOnly script
        run: |
          pnpm prepublishOnly

      - name: Use CLI to create template
        run: node ./dist/index.js create-nhollas-app

      - name: Install vercel CLI
        run: npm install -g vercel

      - name: Pull environment variables
        run: |
          cd create-nhollas-app
          vercel link --yes -p create-nhollas-app --token=${{ secrets.VERCEL_TOKEN }}
          vercel env pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Install template dependencies and run validate
        run: |
          cd create-nhollas-app
          npm run validate-and-test

      - name: Deploy to Vercel
        run: |
          cd create-nhollas-app
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
